### ISSUE TITLE
Question about heap allocated objects

### ISSUE THREAD

**Issue by JosephWagner** [frankmcsherry/timely-dataflow#112]
Hi! I think timely is really neat, and I've been trying to get a handle on it. I have a question about the correct way to send things like Vecs from operator to operator. I'm new to rust so this is probably a dumb question.

In the example below, the compiler says "cannot move out of borrowed content" on the &datum line. What's the proper way to give the vector to the session? Is it `session.give(datum.clone())`? When I try to clone the compiler asks for type annotations and I'm not sure if I'm on the right track.

```
extern crate timely;
use timely::dataflow::{InputHandle, ProbeHandle};
use timely::dataflow::operators::{Inspect, Probe};
use timely::dataflow::operators::generic::unary::Unary;
use timely::dataflow::channels::pact::Pipeline;

fn main() {
    // initializes and runs a timely dataflow.
    timely::execute_from_args(std::env::args(), |worker| {


        // create input and output handles.
        let mut input = InputHandle::new();
        let mut probe = ProbeHandle::new();

        // build a new dataflow.
        worker.dataflow(|scope| {
            input.to_stream(scope)
                .unary_stream(Pipeline, "identity",
                              move |input, output| {
                                  input.for_each(|time, data| {
                                      let mut session = output.session(&time);
                                      for &datum in data.iter() {
                                            session.give(datum);
                                      }
                                  })
                              })
                .inspect(|x| println!("seen: {:?}", x))
                .probe_with(&mut probe);
        });
// feed the dataflow with data.
        let vals = vec![1.0, 2.0];
        input.send(vals.clone());
        while probe.less_than(input.time()) {
            worker.step();
        }
        input.advance_to(1);
    }).unwrap();
}

```

**Comment by frankmcsherry** [comment]
Hi!

This looks like this is a Rust ownership issue. The `session.give` method expects owned data, the `&datum` line would bind owned data to `datum` but Rust isn't happy with this. Calling `clone` should work; I'm not sure what the type annotation issue is (happy to debug that more). 

But! An even better thing to do is probably:

```rust
for datum in data.drain(..) {
    session.give(datum);
}
```

The `drain` method is an operator on vectors (and most collections) that enumerates and removes the contents, providing owned data as output. This means that the `datum` are the owned records themselves and can be directly handed to `session.give`. There are some subtle details (this forces deserialization, which you might be able to avoid with your approach), but if you are just trying to get things to build I would go with `drain(..)` for now.

If you still have the type inference issues, let me know. I don't see anything in your code that is ambiguous, but perhaps it is confused about something else (e.g., which type of floating point representation, `f32` or `f64`). Either way, we can try and figure that out next!

**Comment by frankmcsherry** [comment]
I just tried your example with `data.drain(..)` and all works well. The ambiguity that shows up with `clone()` is, I believe, Rust not knowing which type is supposed to come out of the clone (it could plausibly be `&Vec` or `Vec`), even though you know which one you meant. The `drain(..)` version makes this unambiguous.

Hope this helps!

**Comment by JosephWagner** [comment]
Ah, the `data.drain(..)` idiom worked perfectly. I need to read the Vec docs more closely :)

Thanks for the help!
