### ISSUE TITLE
OS support?

### ISSUE THREAD

**Issue by sanmai-NL** [frankmcsherry/timely-dataflow#130]
I was looking for more information about which OS’es are supported. In particular, whether Windows is supported.

**Comment by frankmcsherry** [comment]
I hope Windows is supported! I has been in the past, though there are occasionally some crates on which timely depends that have surprising behavior (previously, the `mmap` crate, which had broken Windows support).

We've certainly built and run timely on Windows, though I think the last time we checked was about two years back. Timely itself has zero OS-specific code in it, and just uses Rust standard library abstractions and some crates (e.g. for serializing things in what should be OS-agnostic formats).

**Comment by sanmai-NL** [comment]
Great. I was specifically wondering how you’ve implemented IPC for Windows.

**Comment by sanmai-NL** [comment]
Ah, I’m in good hands, seeing you are affiliated with Microsoft Research. ;)

**Comment by frankmcsherry** [comment]
All of the inter-process communication is done via sockets. This ends up working pretty well for a data-driven system, as there isn't as much of a need for e.g. RPC or anything like this. You just establish some typed channels and feed data between the processes (with copies, no shared memory).

I should stress that I'm not at MSR anymore (in fact, I am contractually *obliged* to stress this), and I'm definitely neither using nor testing on Windows. It could be broken, but the last time it was broken (with the `mmap` crate) once we pivoted to a non-broken crate everything seemed to work.

**Comment by sanmai-NL** [comment]
Thanks.
