### ISSUE TITLE
Page Rank enquiry

### ISSUE THREAD

**Issue by florianre** [frankmcsherry/timely-dataflow#157]
Hi,

Regarding the following piece of code:

```
for i in 1 .. 1000 {
      input.send(((rng1.gen_range(0, nodes), rng1.gen_range(0, nodes)), 1));
      input.send(((rng2.gen_range(0, nodes), rng2.gen_range(0, nodes)), -1));
      input.advance_to(1 + i);
      while probe.less_than(input.time()) {
          worker.step();
      }
}
```

Is it performing an edge addition, edge deletion and pagerank update for a 1000 iterations?

Thanks

**Comment by frankmcsherry** [comment]
Yes, that's essentially correct. You could skip the edge updates if you want, and if you'd like to do more than one pagerank update you would need to advance `input` to something more than `i+1`. Should be `i+k` if you want to perform `k` pagerank steps.

There is a [post about the code](https://github.com/frankmcsherry/blog/blob/master/posts/2017-08-21.md) if you haven't seen it, but even if you have no worries asking questions!

**Comment by florianre** [comment]
Awesome I'll have a look as well!! Thanks Frank!
