### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by ynimous** [frankmcsherry/timely-dataflow#16]
I get an error when trying to build this. Not sure why it does not compile. This is with 1.6, but I also tried 1.7-beta and got the same error. HEAD is dee091992aca159de1b7601fdffa9de3d227a9b3

     src/dataflow/channels/pact.rs:21:37: 21:65 error: no associated item named `new` found for type `timely_communication::allocator::thread::Thread` in the current scope
     src/dataflow/channels/pact.rs:21         let (mut pushers, puller) = Thread::new::<Message<T, D>>();
                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
     src/dataflow/channels/pact.rs:23:31: 23:44 error: the type of this value must be known in this context
     src/dataflow/channels/pact.rs:23         (Box::new(Pusher::new(pushers.pop().unwrap(), allocator.index(), allocator.index(), identifier)),
                                                                    ^~~~~~~~~~~~~
     error: aborting due to 2 previous errors
     Could not compile `timely`.

Thanks,

**Comment by frankmcsherry** [comment]
Can you say any more about your build environment / what everything looks like? I just did clean clone and builds on OS X and Ubuntu, and didn't see any issues. Travis CI thinks things are good too.

It is a weird error to see, as `Thread::new()` is right next to the definition of `Thread` in 

https://github.com/frankmcsherry/timely-dataflow/blob/master/communication/src/allocator/thread.rs#L9-L25

**Comment by ynimous** [comment]
I tried a clean checkout, and it compiles without problems. 

The repo that fails to compile is from an old version of the tree, so maybe something does not get recompiled...

I'll just use the clean checkout, but here's my environment for reference:


    $ rustc --version
    rustc 1.6.0 (c30b771ad 2016-01-19)
    $ cargo --version
    cargo 0.7.0-nightly (1af03be 2015-12-08)
    
    
    $ cargo clean
    $ cargo build --verbose
           Fresh libc v0.2.6
           Fresh byteorder v0.4.2
           Fresh getopts v0.2.14
           Fresh winapi v0.2.4
           Fresh byteorder v0.3.13
           Fresh winapi-build v0.1.1
           Fresh abomonation v0.4.0
           Fresh timely_communication v0.1.1
           Fresh kernel32-sys v0.2.1
           Fresh time v0.1.34
       Compiling timely v0.0.12 (file:///usr/src/other/timely-dataflow.git)
         Running `rustc src/lib.rs --crate-name timely --crate-type lib -g --cfg feature=\"default\" --out-dir /usr/src/other/timely-dataflow.git/target/debug --emit=dep-info,link -L dependency=/usr/src/other/timely-dataflow.git/target/debug -L dependency=/usr/src/other/timely-dataflow.git/target/debug/deps --extern timely_communication=/usr/src/other/timely-dataflow.git/target/debug/deps/libtimely_communication-bf55e25cf3d9a922.rlib --extern time=/usr/src/other/timely-dataflow.git/target/debug/deps/libtime-22c21fe32894ddad.rlib --extern abomonation=/usr/src/other/timely-dataflow.git/target/debug/deps/libabomonation-b287cfa226eaa2db.rlib --extern byteorder=/usr/src/other/timely-dataflow.git/target/debug/deps/libbyteorder-bff578a6925be5fe.rlib`
    src/dataflow/channels/pact.rs:21:37: 21:65 error: no associated item named `new` found for type `timely_communication::allocator::thread::Thread` in the current scope
    src/dataflow/channels/pact.rs:21         let (mut pushers, puller) = Thread::new::<Message<T, D>>();
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/dataflow/channels/pact.rs:23:31: 23:44 error: the type of this value must be known in this context
    src/dataflow/channels/pact.rs:23         (Box::new(Pusher::new(pushers.pop().unwrap(), allocator.index(), allocator.index(), identifier)),
                                                                   ^~~~~~~~~~~~~
    error: aborting due to 2 previous errors
    Could not compile `timely`.
    
    Caused by:
      Process didn't exit successfully: `rustc src/lib.rs --crate-name timely --crate-type lib -g --cfg feature="default" --out-dir /usr/src/other/timely-dataflow.git/target/debug --emit=dep-info,link -L dependency=/usr/src/other/timely-dataflow.git/target/debug -L dependency=/usr/src/other/timely-dataflow.git/target/debug/deps --extern timely_communication=/usr/src/other/timely-dataflow.git/target/debug/deps/libtimely_communication-bf55e25cf3d9a922.rlib --extern time=/usr/src/other/timely-dataflow.git/target/debug/deps/libtime-22c21fe32894ddad.rlib --extern abomonation=/usr/src/other/timely-dataflow.git/target/debug/deps/libabomonation-b287cfa226eaa2db.rlib --extern byteorder=/usr/src/other/timely-dataflow.git/target/debug/deps/libbyteorder-bff578a6925be5fe.rlib` (exit code: 101)

Thanks,

**Comment by frankmcsherry** [comment]
Ah, I see. Several of the version numbers are definitely older than they could be. `timely_communication` in particular is now on 0.1.3. 

This is my fault, as I should have set the version requirements to something other than `0.1.*` which allows 0.1.1. I've tweaked it to `^0.1.3` which I think is the "right thing". Sorry!

**Comment by ynimous** [comment]
Yap, this fixes it for me.
Thanks!
