### ISSUE TITLE
Count result absent when no data in some timestamp?

### ISSUE THREAD

**Issue by qiuxiafei** [frankmcsherry/timely-dataflow#167]
Hi, @frankmcsherry !

I have a question about the `Count` operator when there are no data in some timestamp. I think a zero is appropriate, but timely seems to produce no output in this case. For example:

```rust
    timely::execute_from_args(std::env::args(), |worker| {
        let mut input = InputHandle::new();
        worker.dataflow(|scope: &mut Child<_, u64>| {
            scope.input_from(&mut input)
                .count()
                .inspect_batch(|t, d| println!("{:?} {:?}", t, d));
        });
        input.send(999);
        input.send(999);
        input.advance_to(1);
        input.advance_to(2);
        input.send(999);
        input.send(999);
    }).unwrap();
```
I got the following output:

```
(Root, 0) [2]
(Root, 2) [2]
```
A `(root, 1) [0]` is expected because there may be some case where the downstream operators wanna know about the count, even though is just zero, counting the occurrency of each count for example.

After reading some code, I found that the `Count` operator is not notified at all about time `(Root, 1)`, cause the `+1` and `-1` operation on `(Root, 1)` have been merged in `Input` operator, `Count` know nothing about existence of this timestamp.

So, is this kind of behaviour an intended design or something wrong?

**Comment by frankmcsherry** [comment]
Hello.

It's definitely intended. There are some near-infinite number of times at which there is no data, and the uniform way to handle this is to produce no output data when there is no corresponding input data. If you would like to see counts, at times even when there may be no data, you can toss in one additional record at each time of interest and mentally subtract one from the result. That sounds like a quick hack, but it has the advantage that you can stop doing this too, rather than having timely show you counts of zero all the way up to `usize::max_value()` timestamps.

**Comment by qiuxiafei** [comment]
Got it. 

But this sounds a bit hard for users to write the correct code because every operator should care about this special record and decide whether to pass it on or ignore it. It seems not easy when the dataflow gets complex.

**Comment by frankmcsherry** [comment]
Unfortunately, the opposite strategy, of producing a count even when there is no data, has similar problems but is harder for a user to fix (they cannot suppress the 2^64 zero counts that may come out).

It would not be too tricky to write a modified `count` operator that does produce zero counts as records, and which runs forever. You would need to decide what might ever cause this operator to terminate (does it run forever, and one must ^C the computation?), but it would be a good exercise to get a sense for the related issues. If they turn out to be relatively simple, we could look at integrating such an operator.

**Comment by qiuxiafei** [comment]
I am not sure if such a `special_count` is possible if it still doesn't get notified when no data.

Considering a `special_count` get notified in a timestamp sequence of: 1, 2, 3, 5, 6...
When timestamp 3 notified, it shouldn't fire a `(timestamp 4, count 0)` record obviously since it doesn't know if timestamp 4 has finished yet. And when timestamp 5 notified, it's prohibited to send a backward-time message of timestamp 4.

**Comment by frankmcsherry** [comment]
Ah, but when timestamp 3 is notified you can request a notification for timestamp 4, which has the effect of the operator reserving the right to send something at timestamp 4. When that notification fires, you are able to request a notification for timestamp 5 (which may be redundant in this case).

You can also more directly write operators by maintaining `Capability` types directly, rather than relying on the `Notificator`. The notificator can be helpful, but there are times you might want to bypass it. For example, if a range of times are empty (e.g. inputs are 1, 2, 3, 5001, ...) then you would probably prefer to notice that once and send either 4998 zero counts all at once, or perhaps a summary indicating that 4 .. 5000 are empty.

One point this highlights is that sending positive indication of zero counts at each timestamp is going to depend a lot on the ambient timestamp space. E.g. most of our timely examples use nanoseconds as the time domain, and in this case it would be very bad to send data for each timestamp.

**Comment by qiuxiafei** [comment]
Yes, this solution depends on time domain a lot. And in my case it's fine because timestamps are assigned to each input record, they a continues and increasing, not that bad like nanoseconds.

And thanks! It may work, and I'll have a try.

**Comment by qiuxiafei** [comment]
I tried a solution that catching up the gap between the last emitted timestamp and the current one and got a *partially* correct solution like this:

```rust
    timely::execute_from_args(std::env::args(), |worker| {
        let mut input = InputHandle::new();
        worker.dataflow(|scope: &mut Child<_, u64>| {
            scope.input_from(&mut input)
//                .count()
                .unary_frontier(Pipeline, "CountDefault", |capability, _op_info| {
                    let mut stash = vec![];// (capability, sum, valid)
                    stash.push((capability, 0, true));

                    move |input, output| {

                        // collect new input.
                        while let Some((time, data)) = input.next() {
                            stash.push((time.retain(), data.len(), true));
                        }

                        // sort and compact counts.
                        stash.sort_by(|a, b| a.0.time().cmp(b.0.time()));
                        if stash.len() > 1 {
                            for i in 0..stash.len() - 1 {
                                if stash[i].0.time() == stash[i + 1].0.time() {
                                    stash[i + 1].1 += stash[i].1;
                                    stash[i].2 = false;
                                }
                            }
                        }
                        stash.retain(|s| s.2);

                        let mut last_time: Option<Capability<Product<RootTimestamp, u64>>> = None;
                        for (time, count, valid) in stash.iter_mut() {
                            if !input.frontier().less_equal(time) {
                                match last_time {
                                    Some(mut t) => {
                                        // If there's a gap between the last finish timestamp and the current,
                                        // send zero for them.
                                        loop {
                                            let next_time = Product::new(RootTimestamp, t.time().inner + 1);
                                            if next_time.less_than(&time) {
                                                let other = t.delayed(&next_time);
                                                output.session(&other).give(0);
                                                t = other;
                                            } else {
                                                break;
                                            }
                                        }
                                    }
                                    None => {}
                                }
                                last_time = Some(time.clone());

                                output.session(&time).give(*count);
                                *valid = false;
                            }
                        }
                        stash.retain(|(_, _, valid)| *valid);
                    }
                })
                .inspect_batch(|t, d| println!("inspect_batch: {:?} {:?}", t, d));
        });
        input.send(999);
        input.send(999);
        input.advance_to(1);
        input.advance_to(2);
        input.send(999);
        input.send(999);
        input.send(999);
        input.advance_to(3);
        input.advance_to(4);
    })
```
Quite many lines.  The result is: 
```
inspect_batch: (Root, 0) [2]
inspect_batch: (Root, 1) [0]
inspect_batch: (Root, 2) [3]
```
The fixed timestamp is `(Root, 1)`, but `(Root, 3)` and `(Root, 4)` seem not, because I couldn't find an upper bound of timestamp to catch up to. This is the farest to reach in this solution I think.
