### ISSUE TITLE
Make timely a service.

### ISSUE THREAD

**Issue by qiuxiafei** [frankmcsherry/timely-dataflow#169]
Hi, @frankmcsherry !

I'm using timely to build a graph database system recently which serves graph queries. Queries will be interpreted to pre-compiled operators and assembled at runtime. 
Currently, when every query arrives, we simply call `timely::execute` in each process. It's very naive and inefficient to serve queries you know. So I'm considering making timely a service, I'll be very appreciated if you can have some comments!

### My thought follows

To make it a service means:
- Network connections setup when cluster launched, before serving any query.
- When queries arrive, to set up its dataflow, new worker threads are allocated from thread pool or the OS.
- Pre-setup network connections could be reused and shared by all queries.
- Queries run concurrently, the `timely_communication` layer routes messages of different queries correctly.

It may work in this way:
![image](https://user-images.githubusercontent.com/261796/41149184-7ef0f77e-6b3d-11e8-94a4-c770f33d6d88.png)

The interface may looks like: 
```rust
// initially
let svc = new_timely_service(/*come conf*/);

// in some rpc thread or whatever
let query_desc = ....
let guards = svc.submit(job_id, worker_number, |worker| {
                         // dataflow constructed here, from query_desc.
                     }).unwrap();
let results = guards.join();
```

To make multiple queries/dataflow run concurrently, I think the key point is to help `timly_communication` distinguish them. I list the modification needed to made as much as I can:
1. So, at first, let's introduce `JobId`, a universally unique id for each (running) query. Producing such an id seems not difficult, some UUID or a random number may work quite well, so let's assume it.
2. Then, inform the `Binary` allocator of each dataflow about the job id, it will add it to `MessageHeder`.
3. So the `BinarySender` sends messages with extra `JobId` field.
4. `BinaryReceiver` may have to set up multiple `Switchboard`s identified by `JobId`, and route messages of different queries to their own `Switchboard`.
6. `Switchboard`s get disposed on query termination.
5. No modification to `Thread` and `Process` allocators.

**Comment by frankmcsherry** [comment]
Hello! 

This sounds exciting. Before going too far, can you explain what you dislike about the approach where you maintain one timely instance and create a dataflow for each query? Like:

```rust
timely::execute(... , |worker| {

    loop {  // perhaps a better way to shut down?
        
        // see if there is a new query to install, do so.
        if let Some(query) = query_queue.try_read() {
            worker.dataflow(|scope| {
                // build `query` here
            });
        }

        // step each dataflow once.
        worker.step();
    }
})
```

The dataflows are already distinguished at the communication layer, and it seems like this distinction might be repeated above with the concept of a "job".

**Comment by frankmcsherry** [comment]
If it helps, 

1. There is an example of doing this in differential dataflow's [bin/server.rs](https://github.com/frankmcsherry/differential-dataflow/blob/master/server/src/bin/server.rs), which takes in commands from any of the workers and serializes them. It doesn't seem like it hurts throughput, at least when each of the queries are going to involve subsequent computation (it is a broadcast of the "query" to each worker, with a system-wide timestamp).

2. I'm not certain I understand this especially well. If you have a graph shared between some number of workers, what are the cases where you expect to be able to correctly spin up a query on a subset of the workers? You would only have access to a subset of the sharded graph, which could work if you were careful sharding the graph, but which seems a bit sketchy / not commonly likely to work (unless you have some use cases I don't yet grok).
   
    Also, it is totally possible, perhaps independently, to have a dataflow target a subset of the workers by adjusting the exchange functions used. Where we currently use `x -> x % workers` you could just as reasonably do `x -> subset(x)` for your favorite subset. This wouldn't require a fresh set of worker threads, would not do any communication with uninvolved workers (other than them confirming the progress traffic as cancelling).

I'm not trying to be difficult, but I am trying to understand the functionality you require and whether it requires introducing a new layer of abstraction to get it. E.g. if the goal is to be able to concurrently build dataflow across multiple workers, out of order and without synchronizing them, we could scope the identifiers by dataflow and perhaps avoid the introduction of a job concept. If the goal is to be able to restrict coordination to a subset of the workers, that seems like a desirable thing to introduce independent of the concept of a job (e.g. doing process-local aggregation; we currently have "worker-local" and "global", but one could spec out what it would mean to put other restrictions in). If the goal is to have a fresh batch of worker threads to avoid contention, this is a fundamental departure from the timely model and perhaps what you want is `timely::execute(..)` with a re-usable communication layer.

We've set up graph computations where we've gotten (depending on the query structure) between 1k/s and 1m/s query rates. Just doing lookups (e.g. "list neighbors", we've seen throughput in the 10-20m/s range. Is it possible to say a bit more about the types of queries where you think that you can't afford to re-use the existing set of workers?

**Comment by qiuxiafei** [comment]
Thanks, Frank! You're not difficult and your comments help a lot!

I think I should have described my target scenario. I'm building a graph system that handle online and interactive queries. The 'online' part means responding in tens of milliseconds to tens to hundreds of thousands of requests. The 'interactive' part means queries may lasts sub-seconds to minutes, system throughput depends on queries.

I've made a mistake that no clear distinction between `dataflow` and `worker` was made, so I bound a dataflow to a specific worker in my previous design. In limitations 2), I mentioned some special queries spun on a subset of graph partitioins (workers). There're some examples:

- In a graph mixing both knowledge graph and e-commercial graph, queries may touch either one or both. Considering knowledge graph are usually much smaller and traversal in it are deeper, we may duplicate it in every graph partition. If one only queries the knowledge part, it can be served in any worker, otherwise served by all workers.
- Another is Facebook's [Unicorn](https://db.disi.unitn.eu//pages/VLDBProgram/pdf/industry/p871-curtiss.pdf). The whole graph is divided vertically into several `Vertical`s, where each vertical serve only a subset of edge type, saying `friends` vertical and `like` vertical. If a query only care about `friends` relation, it can be pass to `friends` vertical's servers directly.

Considering there's just a few kinds of these special partition strategy, it's possible to set up several process-local, vertical-local, and global instances to handle different types of queries, a head of time or on demand. When a query get compiled, we may have enough information to determine which instance to serve it. And you also mention a solution by adjusting the exchange function, it seems distract a user a bit from the core business logic. But we can also provide some bult-in exchange functions to help. No mater how, this limitation can be resolved.

The last problem is whether to provide a single query entry point. If I understand it correctly, only one of differential dataflow's worker reads stdin, and broadcast the query to everyone. If the query is more complicated than a line of words, a worker thread may parse much less queries per seconds. And if the results are quit large, tens of thousands queries' result data may exhausted the network bandwidth (if the results also return through this single point).

If multiple entry points is necessary, the last problem would be channel ID isolation.

Currently channel IDs are not scoped by dataflow, so differential dataflow's server can not be extended to multiple entry points simply, because it also depends on the assumption that all dataflows are constructed in the same order in all workers, allocating the same channel IDs. So could we introduce a `Dataflow ID` for dataflows to actually scope there channels  (sorry for the previous inappropriate words `Job` and `JobId`) ?

**Comment by frankmcsherry** [comment]
This helps very much, thanks!

I'm going to try and restate things that I think sound like what you might want, in language that I'm more familiar with. If these things seem to line up, excellent, and if it sounds like I am missing an important point please yell at me. :)

1.  I think it is not especially difficult to scope identifiers by dataflow, and we should consider that. 

    At the same time, all dataflow nodes/edges also have scoped names based on the structure of dataflows (e.g. "worker i, dataflow j, subgraph k, ..." -> [i, j, k, ...]). These are not used in binding the channels of the communication plane, but perhaps they can and should be? I think the two distinct flavors currently exist primarily so that logging can avoid allocations (just having a `usize` for each logged item to describe the location), but it might be that we can generally remove them in favor of more clear and descriptive names throughout.  Or it might be that the perf cost of using longer names in e.g. message headers is a big pain. 

    If we want to scope identifiers by dataflow we might want to reason out why *just* dataflow and not e.g. by nested scope, and all the other things that lead to the current hierarchical names (e.g. perhaps "dataflow" is the unit of atomic construction, and within a dataflow it *is* assumed that all participating workers do exactly the same thing, in the same order; perhaps we rule out "I want to construct this subscope before that subscope").

2.  I think it should also be relatively easy to wrap allocators with "worker subsets" so that a dataflow is constructed only knowing about a subset of the workers, with channels "created" for all workers but left inactive for all but the involved workers. At least, I'm having a hard time figuring out where this would go wrong, but of course it could certainly go wrong once we try using it. :) This could either be done carefully and in order to make sure dataflow identifiers remain as they are, on each worker to make sure all identifiers get incremented up, or with identifiers scoped by dataflow so that some workers may not even need to participate in the dataflow construction.

    The intent here would be a mechanism that allows a subset of the workers to participate in dataflow construction, with a bunch of other workers remaining oblivious and not stalling the participating workers by their inaction. The reason that this is different from "new timely instance, with re-used communication plane" is that the timely instance binds a set of workers, and we would like the ability to re-use the worker threads (and data in their thread-local memory) across dataflows that do not need to commit to the same worker sets.

    I'm not 100% certain that the costs of the alternative "just use all workers, but route data to a subset" are well understood. I can believe that there would be costs, and if it turns out that subsetting workers is deeply painful we might want to check out how painful the alternative is. But for the time being, I'm up for exploring / understanding how we would subset workers.

3.  This still strongly associates a "timely instance" with a fixed set of workers, rather than a threadpool or varying sets of machines. This could probably also be relaxed, but it would be easiest without migration of existing dataflows (i.e. new dataflows could see new workers, but old dataflows stay put). Dataflow migration is a thing that some ETHZ folks are working on, but it (currently) requires a restriction to the operators you can write.
