### ISSUE TITLE
Performance degradation observed in timely 0.6.0

### ISSUE THREAD

**Issue by qiuxiafei** [frankmcsherry/timely-dataflow#177]
Hi, Frank!

Recently I've built a timely-server in a way similar to [bin/server.rs](https://github.com/frankmcsherry/differential-dataflow/blob/master/server/src/bin/server.rs), which set up a dataflow in advance and an outside client feeds inputs to worker 0 and results are routed back to worker 0 and then back to outside client. Your comments helped a lot and I'm very appreciative of that!

But after upgrading to timely-0.6.0, about 30% performance degradation is observed, with a few lines of changes in my code for API compatibility.

My timely-server can be simplified as the following:

```rust
extern crate timely;

use std::sync::mpsc::{TryRecvError, channel};
use std::time::Instant;

use timely::dataflow::InputHandle;
use timely::dataflow::operators::{Input, Exchange, Map};
use timely::dataflow::operators::Unary;
use timely::dataflow::channels::pact;
use timely::dataflow::operators::generic::OutputHandle;
use timely::dataflow::channels::pushers::Tee;
use std::sync::Mutex;
use std::sync::Arc;

fn main() {
    let args = std::env::args().collect::<Vec<_>>();
    println!("Starts with arguments: {:?}", args);
    let input_num = args[1].parse::<u64>().unwrap_or(1);

    let (input_send, input_recv) = channel();
    let (output_send, output_recv) = channel();

    let input_recv = Arc::new(Mutex::new(Some(input_recv)));
    let output_send = Arc::new(Mutex::new(Some(output_send)));

    let worker_guards = timely::execute_from_args(std::env::args(), move |worker| {
        let index = worker.index();
        let peers = worker.peers();
        let input_recv = if index == 0 { input_recv.lock().unwrap().take() } else { None };
        let output_send = if index == 0 { output_send.lock().unwrap().take() } else { None };

        let mut input = InputHandle::new();
        let mut timestamp = 0_u64;
        let route = move |vid: &u64| *vid % peers as u64;

        // create a dataflow.
        worker.dataflow(|scope| {
            scope.input_from(&mut input)
                .exchange(route)
                .flat_map(move |vid| {
                    (1..10).map(move |i| vid * 1000 + i)
                })
                .exchange(route)
                .flat_map(move |vid| {
                    (1..10).map(move |i| vid * 1000 + i)
                })
                .unary_notify(
                    pact::Exchange::new(|_| 0),
                    "ResultSink",
                    vec![],
                    move |input, _output: &mut OutputHandle<_, _, Tee<_, u64>>, notificator| {
                        input.for_each(|time, data| {
                            data.take();
                            notificator.notify_at(time.retain());    // for timely 0.6.0
                            //notificator.notify_at(time);             // for timely 0.5.1
                        });

                        notificator.for_each(|cap, _, _| {
                            if index == 0 {
                                output_send.as_ref().unwrap().send(cap.time().inner).unwrap();
                            }
                        });
                    },
                );
        });

        if index == 0 {
            loop {
                match input_recv.as_ref().unwrap().try_recv() {
                    Result::Ok(data) => {
                        input.send(data);
                        timestamp += 1;
                        input.advance_to(timestamp);
                    }
                    Result::Err(TryRecvError::Empty) => {}
                    Result::Err(TryRecvError::Disconnected) => { break; }
                }
                worker.step();
            }
        }
    }).unwrap();

    let start = Instant::now();
    for i in 0..input_num {
        input_send.send(i).unwrap();
        output_recv.recv().unwrap();
    }
    let elapsed = start.elapsed();

    drop(input_send);
    worker_guards.join();

    let elapsed_nanos = elapsed.as_secs() * 1_000_000_000 + elapsed.subsec_nanos() as u64;
    let qps = input_num as f64 * 1_000_000_000.0 / elapsed_nanos as f64;
    let elapsed_ms = elapsed_nanos as f64 / 1_000_000.0;
    let latency_ms = elapsed_ms / input_num as f64;
    println!("Time elapsed (ms): {:.2}, latency(ms): {:.2}, qps: {:.2}", elapsed_ms, latency_ms, qps);
}
```
I run `0.5.1` and `0.6.0` compiled binaries with 16 workers in a single process on a machile which has:
- CPU: 32 Core / Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
- Memory: 128 GB
- OS: Red Hat 7.2
- Rust: rustc 1.27.0 (3eda71b00 2018-06-19)

The expiriment was repeated several times and the result seemed stable. An typicla result like:
```bash
[xiafei.qiuxf@rs3f18021.et2sqa /home/xiafei.qiuxf/learn-rust]
$./test_6  30000 -w 16
Starts with arguments: ["./test_6", "30000", "-w", "16"]
Time elapsed (ms): 2342.53, latency(ms): 0.08, qps: 12806.64

[xiafei.qiuxf@rs3f18021.et2sqa /home/xiafei.qiuxf/learn-rust]
$./test_5  30000 -w 16
Starts with arguments: ["./test_5", "30000", "-w", "16"]
Time elapsed (ms): 1469.59, latency(ms): 0.05, qps: 20413.86
```

The throughput degrates a lot.

To reproduce this problem, I tried pushing all input data into `InputHandle` of worker 0 to mesure end- to end time without waiting for previous query to stop before issue a new one. But there seemed no difference between `0.5.1` and `0.6.0`. The code was like:
```rust
timely::execute_from_args(std::env::args(), move |worker| {
    
    // ...
    worker.dataflow(|scope| { /* ......  */});

    if index == 0 {
        for round in 0..input_num {
            input.send(round as u64);
            input.advance_to(round + 1);
        }
    }
}).unwrap().join();
```

**Comment by frankmcsherry** [comment]
Ah, one thing that I can imagine in such a computer light example is that there may be visible overhead due to the logging infrastructure. Previously this was behind a feature flag, but now it generates and drops events, even if you don't consume them.

This is just a guess, and I'll look into it more, but at the rates you are seeing (50us/iter) the overhead is about 15us/iter, and that could be due to logging. We saw less overhead in the barrier.rs benchmark, but this is a bit different.

Investigation ongoing!

**Comment by qiuxiafei** [comment]
you mean `default_with_env`? I didn't set env variables, it should fallback to original inactive buffering logger by default.

**Comment by frankmcsherry** [comment]
If it is logging, the difference is not the environment variables, but rather that previously logging was compiled out completely. Now log events are constructed and dropped, which we think should have nominal overhead, but perhaps in microbenchmark settings (your example is very close to a coordination microbenchmark) it shows up more prominently than we hoped / saw on other computations.

This is all still a guess though; I'll try and dig in once I'm back from traveling (a week-ish).

**Comment by frankmcsherry** [comment]
Back from travels. One quick point is that your computation is very much a coordination microbenchmark. We can try and figure out what is slowing things down, but the computation does very little work, and instead just coordinates a bunch of workers.

For example, if I run your computation using just one or two threads, I get about 60k qps in both 0.5 and 0.6, for both worker counts. Throughput goes down with more workers, and with the overheads of logging it may be that it goes down a bit more (because each bit of communication is potentially logged, even though the logged events are just dropped).

I need to grab some bigger machines to see about profiling and confirming this theory, but all the pieces seem to fit together.

**Comment by qiuxiafei** [comment]
> One quick point is that your computation is very much a coordination microbenchmark.

Did you mean that each input was assigned a unique timestamp? Yes, this may result to more outstanding timestamps and more progress message. But upgrading from 0.5 to 0.6, I see no significant changes in progress tracking.

By the way, assigning different tiemstamps to different input is my solution to isolate results of these input queries. Maybe there're some better ways I missed.

**Comment by frankmcsherry** [comment]
I meant in the sense that the computation has relatively little computation and data movement, as compared to the amount of coordination it has to do. Part of this is using distinct timestamps for each query, part of it is not bundling input records together, but the main part of it is imposing a system-wide synchronization between each query.

If I take your code and comment out the `output_recv.recv()` in

```rust
    for i in 0..input_num {
        input_send.send(i).unwrap();
        output_recv.recv().unwrap();
    }
```

then the output become

```
Echidnatron% cargo run --release -- 30000 -w1
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/regression 30000 -w1`
Starts with arguments: ["target/release/regression", "30000", "-w1"]
Time elapsed (ms): 2.55, latency(ms): 0.00, qps: 11762524.05
Echidnatron% 
```

which is about 1,000x what you were seeing. This is because that commented line blocks until the computation has produced output, rather than letting the system continue to ingest input and process data in a streaming fashion.

**Comment by qiuxiafei** [comment]
The code I posted was just used to produce the different performance between versions. In my actual timely server, there are multiple `input_send`s, and the server can receive all inputs in the queue at one time, this can be treated as some kind of batch, maybe.

**Comment by frankmcsherry** [comment]
That does sound more appropriate for the system (and its overheads). Do you see the 30% slowdown with the larger amounts of concurrent queries? When I compare 0.5.1 and 0.6 using the version without `output_recv.try_recv()` I see (for 0.5.1 and 0.6 respectively):

```
Time elapsed (ms): 3.47, latency(ms): 0.0001157273, qps: 8641003.46
Time elapsed (ms): 2.57, latency(ms): 0.0000857814, qps: 11657538.81
```

If I crank the per-time batching up to 256 (this is a modified program where each tuple carries a distinguishing timestamp, and times are ticked forward every 256 of them), I see respectively:

```
Time elapsed (ms): 2.08, latency(ms): 0.0000693079, qps: 14428369.64
Time elapsed (ms): 2.12, latency(ms): 0.0000706005, qps: 14164205.64
```

which makes me think that perhaps the overheads aren't so bad in these cases (in fact 0.6 is faster for the first case; not clear why).

**Comment by qiuxiafei** [comment]
Yeah! I got your results reproduced by:

```rust
let batch = 1024;
for i in 0..input_num/batch {
    for j in 0..batch {
        input_send.send(i * batch + j).unwrap();
    }

    for _ in 0..batch {
      output_recv.recv().unwrap();
    }
}
```
and got the results:

```
v6	Time elapsed (ms): 1957.05, latency(ms): 0.01, qps: 153291.60
v5	Time elapsed (ms): 1933.93, latency(ms): 0.01, qps: 155124.84

```

I think it should be enough to conclude that: if there are enough concurrent ongoing timestamps in system, the progress tracking overhead can be ignored.
