### ISSUE TITLE
Race leading to deadlock

### ISSUE THREAD

**Issue by frankmcsherry** [frankmcsherry/timely-dataflow#198]
Reported by @siddharthasahu 

If you spin up two processes with two worker threads each, running the `hello` example often enough, you eventually hit a deadlock where the two processes do not shut down. It took a while for me to see it, but you do reach something that looks like (the killing happens once you are bored, not before):

```
echidnatron% cargo run --release --example hello -- -n2 -w2 -p0
    Finished release [optimized + debuginfo] target(s) in 0.06s                                                                                               
     Running `target/release/examples/hello -n2 -w2 -p0`
worker 0:	hello 0
worker 1:	hello 1
worker 0:	hello 4
worker 1:	hello 5
worker 0:	hello 8
worker 1:	hello 9
^C
```

and 

```
echidnatron% cargo run --release --example hello -- -n2 -w2 -p1
    Finished release [optimized + debuginfo] target(s) in 0.06s                                                                                               
     Running `target/release/examples/hello -n2 -w2 -p1`
worker 1:	error connecting to worker 0: Connection refused (os error 61); retrying
worker 2:	hello 2
worker 3:	hello 3
worker 2:	hello 6
worker 3:	hello 7
thread 'recv thread 0' panicked at 'assertion failed: read > 0', communication/src/allocator/zero_copy/tcp.rs:64:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'Recv thread panic: Any', libcore/result.rs:945:5
```

No information yet on what is going wrong, but there are for sure a few spots where the data could be getting dropped, buffers could be not flushed, and threads could be not awoken when they should be.

More information once I get this reproducing a bit more consistently, with a read-out of what must have happened / which invariant broke first.

**Comment by frankmcsherry** [comment]
Recently added: a differential dataflow program to sniff around at the disparity between sent and received data:

    https://github.com/frankmcsherry/differential-dataflow/blob/master/examples/logging-recv3.rs

This lets you start up a log analysis program in differential, like so:

    cargo run --release --example logging-recv3 -- 0 4 1

which starts listening for 4 communication threads and produces results every second. No results until the threads connect, though.

Elsewhere, you might type

    TIMELY_COMM_LOG_ADDR="localhost:9000" cargo run --release --example bfs -- 10000000 100000000 -n2 -w8 -p0
    TIMELY_COMM_LOG_ADDR="localhost:9000" cargo run --release --example bfs -- 10000000 100000000 -n2 -w8 -p1

which enables communication logging at the port hard-coded into logging-recv3. This will do a bunch of compute, feed the logging program, and it will produce output like

```
cargo run --release --example logging-recv3 -- 0 4 1          
    Finished release [optimized + debuginfo] target(s) in 0.08s                                                                                               
     Running `target/release/examples/logging-recv3 0 4 1`
starting with work peers: 0, comm peers: 4, granularity: 1
SEND: (3, 1s, 118802120)
SEND: (4, 1s, 448)
SEND: (10, 1s, 101632)
SEND: (3, 2s, 23445176)
...
LATE: ((10, 6912), 59s, 1)
LATE: ((10, 6912), 60s, -1)
LATE: ((10, 35488), 58s, -1)
```

which tells us about the numbers of bytes sent and received on each timely channel, as well as their difference (`LATE`).

**Comment by siddharthasahu** [comment]
The socket state for one of the processes is FIN_WAIT2 while the other is CLOSE_WAIT. 
Not sure if it helps, but this would mean one of the processes (the one waiting for the 0 length header) does send a close signal to the other one.

**Comment by frankmcsherry** [comment]
I'm still able to repro it (unfortunately, I apparently had a good run after the last fix). I'm seeing something weird that I don't get yet, where a queue is filled with a record (under a mutex) and then observed to be empty (under a mutex) without a drain in between.

This lines up with your socket observation, in that one process believes it is done because it sees a few empty queues once the workers go away, but .. they shouldn't be empty. Because .. they were filled just a moment ago and no intervening instructions drained them.

I'm sure it will be something silly; I've got eyes on the defective behavior, though.
