### ISSUE TITLE
Timely monitoring tool

### ISSUE THREAD

**Issue by qiuxiafei** [frankmcsherry/timely-dataflow#212]
Hi, Frank!

Recently we're working on an early demo of a timely monitoring/analytic tool to answer a simple question: why does my query run so slow? The questing can then be broken up into two parts, 1) is there any operator consuming lots of CPU time? 2) is there any channel transferring too many messages?

Before making this tool too fancy (or complex), we decided to work on the most naive stuff first,  collecting, storing all timely logs and showing them to users in a helpful and comfortable way. This is to make timely transparent.

I wanna know if there's anything similar we can leverage or learn from? I saw [timely-viz](https://github.com/utaal/timely-viz) months ago, it seemed to target real-time analysis by displaying fresh events in a web browser. It remained inactive for quite a long time and reactive again in recent days. I don't know if there are any other tools like timely-viz?

Thanks!

**Comment by frankmcsherry** [comment]
Hello!

This sounds fun! The timely-viz project is related, and while it has been quiet for a while I think it is ultimately meant to work / be supported (though at the moment @utaal may have relatively few free cycles). Also relevant, @comnik and friends have a similar plan for their [3DF framework](https://github.com/comnik/declarative-dataflow), though I'm not certain of the state of the project at the moment.

I personally mostly do `logging-recv2.rs`-style differential computations, which isn't a great user-facing experience, but has been "sufficient" for most questions I've had. So, perhaps differential gets you a bit of mileage (which the other two projects have used too).

I'm currently checking out the logging infrastructure, as something about it is slowing down computations more than I would expect. And fixing up bugs you all have pointed out. :)

**Comment by qiuxiafei** [comment]
Thanks, Frank!

I'll put an eye on these projects you mentioned. Maybe different tools are required in different application scenarios, I'm not sure. But I know our tool is targeting the production-ready and user-friendly part because its users are not timely developers. If the tool proves to be useful in the future, maybe we can open source it and contribute back to timely community.
