### ISSUE TITLE
Generic aggregate operator

### ISSUE THREAD

**Issue by sga001** [frankmcsherry/timely-dataflow#27]
I've been thinking about implementing a generic aggregate operator (e.g., a reduce in MR lingo), since I've found myself writing the same pattern over and over.

The way I currently do aggregation is through a combination of unary_notify + state (let me know
if this is not the way to go!). It usually looks something like this:

```
let state =  // some collection (perhaps a HashMap<Timestamp, Vec<T>>). 

stream.unary_notify(Pipeline, "aggregate", vec![], |input, output, notificator| {
  input.for_each(|time, data| {
    notificator.notify_at(time.clone());
    state[&time].append(data.drain(..).collect());
  });

  notificator.for_each(|time, _| {
    let aggregate = //perform aggregation logic for all values of state[time]
    output.session(&time).give(aggregate);
   // garbage collect state[&time]
  }
}
```

Sometimes it is possible to update ``state`` as you go instead of appending to a list and updating at the end. So it'll look like this:

```
let state =  // some collection (perhaps a HashMap<Timestamp, T>). 

stream.unary_notify(Pipeline, "aggregate", vec![], |input, output, notificator| {
  input.for_each(|time, data| {
    notificator.notify_at(time.clone());
    state[&time] = // aggregation_logic(state[&time], data)
  });

  notificator.for_each(|time, _| {
    output.session(&time).give(state[&time]);
    // garbage collect state[&time]
  }
}
```

I was wondering if it would be easy to generalize these two cases so one can just do:

```
stream.aggregate(|x: Vec<T>| { aggregation logic that acts on x })  
```

```
stream.aggregate_it(|x: T, y: T| { aggregation logic in terms of x and y } )
```

Does this seem like a good idea? I think that all that would need to be done is something very similar to the way unary_notify is implemented (in unary.rs), but extend the struct Operator to incorporate this extra state (in addition to writing the necessary boilerplate)?

Any thoughts? Apologies if this is already covered by differential_dataflow's ``group`` operator (I honestly couldn't make sense of it).

**Comment by frankmcsherry** [comment]
It definitely isn't covered by `group`, no worries. :)

When I've done this before, I've written something that takes `(K,V)` pairs, and is generic in an aggregation type `S` (for state) and a function `F: Fn(&K, V, &mut S)`. The intent is that as you get new data, you can describe how to update the state. 

Perhaps if you can update in place your function is

    |k, v, s| { *s += v; }  // S is just i64, maybe

or perhaps if you need to build everything up first it is

    |k, v, s| { s.push(v); }  // S is Vec<V> perhaps

In either case, the infrastructure for shuttling the data around stays the same. You probably also want a `G: Fn(S)->R` to produce the result from the state when finished, and maybe a few other combiners (e.g. `C: Fn(S, S)->S` to merge states accumulated at different times).

The main downside of this approach used to be that if you wanted a list of records you might want to manage the lists in some tighter way. Differential uses a linked list backed by one allocation, whereas the above would have allocations for each key. That would be a disaster in Java/.NET, but maybe in Rust it isn't so horrible. It is at least worth trying. :)

If you'd like to try this out, that would be great! If you'd rather have a version whipped up for you, I could totally do that (really, I should have a while back, as there have been a few times where folks have wanted this and had to hand roll instead).

**Comment by frankmcsherry** [comment]
I [just pushed](https://github.com/frankmcsherry/timely-dataflow/commit/1e2dcc994ec0dee25c564f9eb1d2909202d6dbe7) some code that does roughly the above.

I took the pattern we used in Naiad, where you have two types of methods, respectively:

1. `aggregate`: performs aggregation within times, using user supplied types and logic, and producing at most one output for each key, for each time. 

2. `state_machine`: observes a stream of keyed events, and has the option to produce output for each. 

You may only be interested in `aggregate`, and there are [two examples (tests, even!)](https://github.com/frankmcsherry/timely-dataflow/blob/master/src/dataflow/operators/aggregation/aggregate.rs#L70-L94) that do the two types of aggregation we discussed:

```rust
#[test]
fn it_works() {
    ::example(|scope| {

        (0..10).to_stream(scope)
               .map(|x| (x % 2, x))
               .aggregate(|_key, val, agg| { *agg += val; }, |key, agg: i32| (key, agg), |key| *key as u64)
               .inspect(|x| assert!(*x == (0, 20) || *x == (1, 25)));

        (0..10).to_stream(scope)
               .map(|x| (x % 2, x))
               .aggregate::<_,Vec<i32>,_,_,_>(|_key, val, agg| { agg.push(val); }, |key, agg| (key, agg.len()), |key| *key as u64)
               .inspect(|x| assert!(*x == (0, 5) || *x == (1, 5)));
    })
}
```

The documentation isn't really there yet (some rambling for `aggregate`; nothing much for `state_machine`), but let me know how this looks to you and I can tidy it up.

**Comment by bfrog** [comment]
I like the aggregate function there and the usage of it, seems nice!

**Comment by kali** [comment]
Indeed, it looks like it will simplify greatly trivial reduction cases.
