### ISSUE TITLE
timely-0.0.13/src/execute.rs:22:5: 26:7 error: mismatched types:

### ISSUE THREAD

**Issue by azywait** [frankmcsherry/timely-dataflow#32]
Hi,
I found an issue.
When I use the example of hello.rs, it shows an error as follow:
![image](https://cloud.githubusercontent.com/assets/4987859/14696953/4a204e46-07b2-11e6-9b0d-df76249febda.png)
Cargo.toml as follow:
![image](https://cloud.githubusercontent.com/assets/4987859/14697058/2ea800a4-07b3-11e6-8993-b2e742dc5662.png)
Rust version:
![image](https://cloud.githubusercontent.com/assets/4987859/14697074/45005464-07b3-11e6-916d-b811f241b32c.png)
I think the version of timely crate from crates.io is old. When I replace the source code using
`https://github.com/frankmcsherry/timely-dataflow`
in:
`/home/hduser/.cargo/registry/src/github.com-88ac128001ac3a9a/timely-0.0.13`
it works.
So, it need to update timely crate in crates.io ??

**Comment by frankmcsherry** [comment]
Yeah, this is my bad. I pushed a new and improved `timely_communication` crate which wasn't backwards compatible, and my semver wasn't good enough. I'll push an improved `timely` which should make things better. :)

**Comment by frankmcsherry** [comment]
v0.0.14 now live; I think it should fix the problem you are seeing (at least, I don't see it now myself). Let me know if it looks good to you!

**Comment by azywait** [comment]
v0.0.14 is ok!
![image](https://cloud.githubusercontent.com/assets/4987859/14702918/b9ce7e16-07df-11e6-8429-b5caff6c0221.png)
Thanks for your help!
