### ISSUE TITLE
Failure building due to name "Timely Dataflow Test"

### ISSUE THREAD

**Issue by jwvictor** [frankmcsherry/timely-dataflow#33]
Build failed due to the spaces in the name of the crate. I expect this is a vestige of an older version of Cargo, but still happens when you import the dependency via crates.io. Seemed to fix itself when I manually compiled the timely-dataflow git repo.

**Comment by jwvictor** [comment]
Update: that trick only worked when I was using nightly on multirust... otherwise I get this error:

```
   Compiling Test Timely Dataflow v0.0.1 (file:///var/binder/code/test-tdf)
error: invalid character ` ` in crate name: `Test Timely Dataflow`
error: invalid character ` ` in crate name: `Test Timely Dataflow`
error: aborting due to 2 previous errors
Could not compile `Test Timely Dataflow`.
```

**Comment by frankmcsherry** [comment]
Just touching in on this: I *think* what it is complaining about is the space in your crate name: `Test Timely Dataflow`. I am often wrong about such things (diagnosing bugs remotely), but that is my best guess. If all looks good when changed to, e.g., `TestTimelyDataflow` then I'd guess that's it!

**Comment by jwvictor** [comment]
Dr. McSherry -

Yes indeed, that was the resolution! What a rookie mistake. Thank you so
much for having a look -- I'm absolutely fascinated by the work you're
doing with Timely Dataflow and I'm planning to build some machine learning
stuff using it. Will be sure to keep you updated!

Thanks again,
Jason

**Comment by frankmcsherry** [comment]
No worries. :)

Let me know if you have any questions about ML stuff. There are some async ML prototypes for SGD style learning that might be helpful!
