### ISSUE TITLE
Scopes should separate channel allocation and operator ownership

### ISSUE THREAD

**Issue by frankmcsherry** [frankmcsherry/timely-dataflow#36]
The current scope design has one struct that manages both channel and identifier allocation, and operator ownership. Because of the former, the scopes get cloned all over the place so that folks can create channels and identifiers. Consequently, ownership gets cloned all over the place and we end up with reference cycles, and resources don't get released until operators are tombstoned (which is not guaranteed to happen). 

Obviously this is horrible if you rely on releasing resources (or have any standards at all).

The fix doesn't seem too complicated: scopes like `Root` and `Child` should clearly distinguish between the cloneable `Allocator` types they have, and the non-clonable operators they own. When we need to clone a scope, we should determine that we only need the `Allocator` component (otherwise: weird), and just clone that.

Specifically, where `Root` currently looks like

```rust
pub struct Root<A: Allocate> {
    allocator: Rc<RefCell<A>>,
    graph: Rc<RefCell<Vec<Box<Operate<RootTimestamp>>>>>,
    identifiers: Rc<RefCell<usize>>,
}
```

calls to allocate channels and identifiers currently resolve to the first and third fields. These two should be bundled up into something called `Allocator` or so, and made available. At the same time, it would be helpful to remove the `Clone` implementations from scopes, as well as their `Rc` wrappers around owned operators, to clarify the single ownership.

**Comment by frankmcsherry** [comment]
Also, I'm on this one, so no ninja pull requests fixing it for me. :)

**Comment by kali** [comment]
oh good. I half tried doing it at some point a few months ago but never got to the end of it.

**Comment by frankmcsherry** [comment]
More investigation reveals that the problem wasn't exactly cycles in scope ownership, which can't easily happen (the `Child` scopes own clones of their parents, but the parents do not naturally point at `Child` children).

Rather, the problem seemed to resolve to a scope getting captured by the closure of an operator, which is another problem altogether. The current fix is meant to be minimally invasive, and amount to extracting `Subgraph` from it's `Rc<RefCell<_>>` container before adding it as an operator. This ensures that the subgraph is uniquely owned. The downside is that it happens at graph construction time, rather than compile time.

Looking forward, the way scopes work could use some love. They have had many flavors over the years, where they were sometimes `&mut` references to ensure exclusive access, sometimes `&` references to try to avoid references escaping, but they have been ergonomically painful. Perhaps with more Rust experience the right pattern will emerge to provide static guarantees that references to scopes do not escape the scope construction, but I don't see it at the moment.

**Comment by frankmcsherry** [comment]
I like how #37 addresses the encountered issue (cycle from a `Subgraph` back to its `Child` scope), so I'm going to close this for now. There is still lots of potential to clean up how children reference their parents, and whether they should get to things like channels / (index/peers) / logging through their parents or just with a shared `Rc<RefCell<_>>`. 

Yes, I said logging. ...
