### ISSUE TITLE
Stream ergonomics vs code complexity

### ISSUE THREAD

**Issue by frankmcsherry** [frankmcsherry/timely-dataflow#8]
The `Stream` type presently wraps a `G: Graph` reference so that it is fully capable of attaching itself to an operator in the graph with no additional help. This introduces some annoyances, in that the `Stream` type also needs a lifetime, and these are some times mysterious borrows and runtime panics that might not be expected (the programmer needs some discipline to not try and access the graph twice at the same time).

An alternate approach, less appealing from the ergonomics point of view but a bit simpler, is to require that methods on `Stream`, things like `map`, `filter`, `concat`, each take a `&mut G` in addition to other arguments, and to keep the `Stream` itself from managing this reference.

The intent here is to see if it is possible to leverage Rust's own borrowing constraints to statically provide the constraints that `RefCell` enforces dynamically. If `graph` is exclusively borrowed, perhaps because a subgraph has borrowed it to do some work, it is unavailable for others to use. This would disable graph manipulation anywhere other than the current subgraph.

Code that previously looked like:
```rust
let result = stream.concat(&mut other)
                   .distinct()
                   .map(|x| x + 1);
```
would instead look like
```rust
let result = stream.concat(&mut other, &mut graph)
                   .distinct(&mut graph)
                   .map(|x| x + 1, &mut graph);
```
Perhaps the ergonomics can be improved if the methods act on pairs `(Stream, &mut G)`:
```rust
let result = (stream, &mut graph).concat(&mut other)
                                 .distinct()
                                 .map(|x| x + 1)
                                 .0;
```
Or slightly differently, pedagogically:
```rust
let result = stream.enable(&mut graph)
                   .concat(&mut other)
                   .distinct()
                   .map(|x| x + 1)
                   .disable();
```
This is basically stating explicitly what we expect to happen with the `RefCell<&mut G>` in the current implementation, but statically enforced.

Although the code here looks more pained, I would imagine improvements to the respective bits of code related to setting up `RefCell<&mut G>` guards and ensuring that they live long enough but not too long. However, it may be that zero people spend time setting up subgraphs, and far more want to use the iterator-looking syntax.

## Lifetimes

A downside to the proposed approach is that `Stream` having a lifetime has the potential (I'm not sure about guarantee) to only allow streams to interact with streams from the same subgraph scope. Without the lifetime constraint they would be able to interact with any other stream with the same `G: Graph` type, which could be a different subgraph (though, with the same timestamp). Needless to say this would cause other runtime issues (panic would be the best case).

It seems like `Stream` could keep its lifetime independent of the above choice. The lifetime wouldn't be used as part of a reference, just to constrain each `Stream` to have a common lifetime, presumably set by the subgraph `enter` function, which would use the lifetime of the subgraph reference. We wouldn't get a simpler `Stream` with the above proposal in this case, just one that has better static guarantees about graph structure.

**Comment by frankmcsherry** [comment]
One of the supposed advantages to doing things the way we have is that one should be able to do either / both! The existing `Stream` type lives in the `src/example/` directory because all that stuff was meant to be an example of using timely dataflow, not the only way. So, I should be able to try this out in parallel, for example in `/src/example-static/`, which I'm now doing!

**Comment by frankmcsherry** [comment]
I'm going to claim this is [fixed by this commit](https://github.com/frankmcsherry/timely-dataflow/commit/d1b1b2e47ce59619078c3cdb6e47384cbfe86ebb), which introduces a `src/example_static` directory with analogues of `src/example/` except each much simpler. There is also a `examples/main_static.rs` which parallels `main.rs` but using the new streams, and the examples are currently much shorter and simpler.

I'll keep trying out the new streams and try and get a feel for their ergonomics. The main issue is understanding how often one needs to `enable`/`disable` the streams in a real setting.

**Comment by gereeter** [comment]
I have a handful of comments here.

First, I think I greatly prefer the statically enforced API - it requires thinking about fewer lifetimes  (to avoid `RefCell` conflicts), has less chance of causing runtime errors, makes the internal code cleaner, and just generally seems to have fewer moving parts.

Second, I think that the important difference between the two approaches is not the move from `&RefCell` to `&mut` but the split of `Stream` and `ActiveStream` and the fact that the adaptors (`map`, `distinct`, etc.) take the `ActiveStream` by value. If we had `impl Graph for &RefCell<Graph>` and `ActiveStream` and `SubgraphBuilder` took their graphs by value, it would be possible to mix and match approaches (I should have a PR for this up soon).

Third, the splitting of `ActiveStream` and `Stream` allows for some interesting improvements. It removes the previous awkwardness of having to choose which graph to use when joining multiple `Stream`s in things like `concat`. Additionally, it opens the door for future improvements, like fusion. Previously, if you called `stream.map(f).map(g)`, there would be no way for the system to prove that the results of the first `map` would only be used by the second `map`, preventing any combination into `stream.map(|x| f(g(x)))`. In constrast, with `ActiveStream`s that are consumed when `map`ped, it should be possible (with some fiddling) to do this transformation and speed up code.
