### ISSUE TITLE
Reviewing motivation sections in the book

### ISSUE THREAD

**Issue by shamrin** [frankmcsherry/timely-dataflow#86]
* I haven't got the general approach you take to solve word count problem.  Yes, you have a couple of queues, but it's not super clear to me why you need them. I think (but I can be mistaken) it would help if you state in a couple sentences what is the general approach, and then proceed to the code. The best place seems to be at the beginning of ["Maintaining word counts" section][1]. May be the problem is that I'm that familiar with big data research.
* Why not name the variable `time` instead of `key`? Then you wouldn't need to say that ["`key` was `time` before"][2] in a couple of places.
* ["Even just writing something like `grep`, by stating your program as a dataflow computation its implementation immediately scales out to multiple threads, and even across multiple computers."][3] I didn't get the `grep` reference. Could you clarify please? Some words seem to be missing.
* ["The intent of the research project is to remove layers of abstraction fat that prevent you from expressing anything your computer can do efficiently in parallel."][4] Change "the research project" to "this research project" or just "this project"?

[1]: https://github.com/frankmcsherry/timely-dataflow/blob/e7e2721d7771fcfd0ad6c44c2469ab5ab883aa08/mdbook/src/chapter_0_1.md#maintaining-word-counts
[2]: https://github.com/frankmcsherry/timely-dataflow/blame/e7e2721d7771fcfd0ad6c44c2469ab5ab883aa08/mdbook/src/chapter_0_1.md#L210
[3]: https://github.com/frankmcsherry/timely-dataflow/blame/e7e2721d7771fcfd0ad6c44c2469ab5ab883aa08/mdbook/src/chapter_0_2.md#L13
[4]:  https://github.com/frankmcsherry/timely-dataflow/blame/e7e2721d7771fcfd0ad6c44c2469ab5ab883aa08/mdbook/src/chapter_0_2.md#L17

Finally, the following two statements on ["When to use Timely Dataflow" section](https://github.com/frankmcsherry/timely-dataflow/blob/master/mdbook/src/chapter_0_2.md) helped me a lot to understand things. Thank you!

> Timely dataflow is a dataflow system, and this means that at its core it likes to move data around.

> Dataflow systems are also fundamentally about breaking apart the execution of your program into independently operating parts.

**Comment by frankmcsherry** [comment]
1. I added a bit more description of the intended wordcount algorithm, both at the top of the section where I give a sequential version we are going to mirror, and later on in the section you mention where (I think) there is now motivation for each of the weird things that happens in the code.

2. I find that `time.time()` looks odd. The `key` is actually a `Capability<T>` rather than a time, but it is most helpful to think of as a time (the capability aspects are mostly hidden). Perhaps what it needs is a `Deref<Target=T>` implementation, at which point the `.time()` goes away, but this is blocked on changes to the code (though, writing docs is a good way to see how you would rather the code be).

3. I added some missing words. I'm not sure which part was least clear (was it that `grep` wasn't well defined; that was the only thing I expanded).

4. Changed!

**Comment by shamrin** [comment]
Thank you!

Regarding `grep` reference, I was confused by "just". You've changed it to "when", and now it's good:
> Even ~~just~~ when writing something like `grep`, …

-------------------------------

Regarding the word-count problem, showing sequential Rust program was indeed very helpful.

I have a question about the [new paragraph][1] mentioning "racing ahead of the others" and "data out of order":

> Having exchanged the data, each worker will need a moment of care where it ensures that it hasn't raced ahead of the others and might be processing data out of order. The operator will enqueue batches of word updates, and await the signal that all such batches at that time have been consumed.

Why is avoiding "rac[e] ahead of the others" important? If I'm not mistaken, words are distributed across workers. Each word is processed at one and only one worker. What could go wrong?

I *think* I understand why "out of order" updates could produce wrong counts. E.g., shuffling around +1, +1, +1, -1 for a single word could produce too large or too small interim count. (However, it could probably be helpful to show the failing example in the book. Thinking about order seems hard.)

[1]: https://github.com/frankmcsherry/timely-dataflow/blame/36bc2e6b1db914b2433e58a40834df59d629c8f8/mdbook/src/chapter_0/chapter_0_1.md#L131

**Comment by frankmcsherry** [comment]
An example is a good idea. Explaining the issue requires forcing the "streaming" aspect of the input a bit more, which is probably good to do.

Roughly, you could imagine multiple workers with inputs

    worker0 @ time 1: "hello world", +1
    worker1 @ time 2: "hello", +1
    worker0 @ time 3: "hello", -1

where the intended output for `"hello"` is `1, 2, 1`. However, without coordination there could be other possible outputs, including `1, 0, 1` if worker 0 does both of its updates without waiting for worker 1.

Thank you for the feedback!

**Comment by shamrin** [comment]
Your example shows something I haven't previously considered. Does worker 0 sends `"hello"` to worker 1? If yes, where does it happen in the demonstrated word-count operator?

**Comment by tschottdorf** [comment]
The word count example uses an Exchange to determine the worker based on the length of the string. So basically with two workers, worker0 receives even length, worker 1 the rest. So you'd need to add a char somewhere for the example strings to actually go to different ones :)

**Comment by frankmcsherry** [comment]
@shamrin The secret, understated moment is with the `Exchange` operator supplied. It could be embellished to be clearer.

@tschottdorf Yes.. *grumble*... :)

**Comment by frankmcsherry** [comment]
@shamrin By the way, one thing I could do is develop a sequence of *incorrect* implementations, in each case revealing the defect that went unnoticed. For example, start with a `Pipeline` data exchange that doesn't put all instances of a word at the same place, then fix that but not consider out-of-order data arrival, etc.

I'm hesitant to do this, because it focuses some attention on defective implementations. But perhaps it is better rhetorically to explain what could have gone wrong.

**Comment by shamrin** [comment]
@frankmcsherry I would read the sequence of incorrect implementations with great interest! But if you want me to find reasons not to write it this way, I see at least two:

1. It would make this section of the book longer. 
2. It would simplify the learning too much and make it too unchallenging. Struggling while figuring out what's wrong seems to be an important part of learning. But I'm very likely exaggerating. And there are ways to overcome it. For example "try running the program with this input; what do you get? can you figure out what's wrong? try to understand it on your own first; only then continue reading further". Unfortunately, all these extra words would also contribute to section length.

Unhelpful conclusion: I don't know.

**Comment by frankmcsherry** [comment]
I think this is all good stuff to do for learning, but I worry that it might be a bit much for "your first taste of timely dataflow". Maybe I should re-org a bit and take the "simple example" from the introduction into this section instead, have the "good for", "not good for" sections, and then perhaps do a longer "let's build a complete program" section (before operators and execution? seems like we are jumping the gun on them too).

**Comment by shamrin** [comment]
I've just read an updated motivational sections. Awesome! Previously it was overwhelming, as you've probably noticed from my questions. Now it's much more manageable. With this update you've also answered the question that I had in my mind, but didn't ask: "where's the proper multi-process example?" Thank you!

If you don't mind, I'll send you more GitHub pokes when I'll finish reading the guide. This issue should be largely closed, except one small confusing I had:

Is there any principle with which `0..10` numbers get distributed across workers? if yes, what is it? It would be nice to see this principle mentioned in the section. I didn't feel the need for the "how" explanation, because the section itself felt like a mysterious bait to make me read the guide further. Just the "what" what be enough for me.

There's also a minor problem with this sentence:

> To do this, you use the `-n` and `-p` arguments, which tell each process how many other processes to expect (the `-n` parameter) and which index this process should identify as (the `-p` parameter).

"Other" seems incorrect to me. According to example, `-n` tells how many process to expect *overall* (i.e. including the current process).

**Comment by frankmcsherry** [comment]
1. The numbers should all be introduced by worker zero, because of the guard on `input.send`, and then .. the only *guarantee* is that records that evaluate to the same integer in the `exchange` closure go to the same worker. In practice this means that records that evaluate to `i` go to worker `i % #workers`, but this is the sort of thing that might change in the future (imagine, hypothetically, adding workers to a computation).

2. You are correct! It should be "how many *total* processes to expect".

**Comment by shamrin** [comment]
Closing, because 94c085f. Looks great now!
