### ISSUE TITLE
Possibility of Timely-dataflow in HPX- C++Runtime system based on PARALLEX!

### ISSUE THREAD

**Issue by preejackie** [frankmcsherry/timely-dataflow#95]
Hi Guys ! 
I'm PraveenVelliengiri a student from India. I did Google Summer of Code - 2017 for STE||AR Group on the Project Idea Distributed Component Placement. https://summerofcode.withgoogle.com/projects/#6358041686441984. 
I have recently(2 days before) came across the term " Timely Dataflow". I'm not sure what it about, but I found you Guys have docs and blogs I need to look into these. I don't know Rust though, the code base "amaze" me. In the first place I need to ask you Guys what Timely Dataflow all about ?
How it is different from Google Dataflow Model ? 
I willing to implement it for the HPX - C++ runtime System https://github.com/STEllAR-GROUP/hpx. 
HPX has a implementation of Dataflow- Local Control Object, 
It's functionality is to support Async computations. 
First Let me explain its use case.

hpx::future - represent the result of async computation, whose result is not known yet !
hpx::future<T>   f1  = // some lambda 
hpx::future<T2> f2  = // some other lambda 
......
hpx::future<Tn> fn  = //some mess 

hpx::dataflow( associates , func); - Although it's not a correct syntax, it is good for explaining the meaning. 
 associates - represents the futures the dataflow is associated.
Dataflow will spawn a task (don't wait) once the associated futures(*) became ready and executes the corresponding the function(func) on the worker thread. Unfortunately, HPX has this one implementation for the support for dataflow. So I like to implement things which support to represent dataflow in the Program. I clearly don't know whether timely dataflow is related to this. But I'm just trying to get the essence of timely dataflow. 
Whether timely dataflow is only suitable in batch-stream Processing ? whether it makes sense to implement it in some Runtime System which supports Parallel and distributive computing. It generally sits between OS and Application.
What time really represents whether its the time to execute a certain piece of code or whether the time to notify from some node for data, what actually it means ?
Would you please explain some example related to timely ( please in a pseudo-code style ) because I don't know Rust : ) Sorry for Submitting this as an issue, I don't find any communication medium to get you people though...
Please reply
Thanks
Praveen

**Comment by frankmcsherry** [comment]
Probably the best place to start with timely dataflow in a language-agnostic presentation is 

https://www.microsoft.com/en-us/research/publication/naiad-a-timely-dataflow-system-2/

The work pre-dates Google Cloud Dataflow, so I'm afraid you'll have to ask them about the differences (or find someone familiar with both; I'm not as clear on what GCD is or how it works other than the paper, which .. was also unclear).

**Comment by frankmcsherry** [comment]
It's been a year, and going to close due to inactivity. Feel free to open up if energy returns!
