### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by de-code** [frankmcsherry/timely-dataflow#97]
Hi,

I'm not really familiar with Rust so apologies if that is a user error. I am trying to run your pagerank and I am getting this:

>    Compiling timely v0.2.0
> error[E0599]: no method named `pop` found for type `timely_communication::allocator::thread::Pusher<dataflow::channels::message::Message<T, D>>` in the current scope
>   --> /home/.../.cargo/registry/src/github.com-1ecc6299db9ec823/timely-0.2.0/src/dataflow/channels/pact.rs:26:39
>    |
> 26 |         (Box::new(Pusher::new(pushers.pop().unwrap(), allocator.index(), allocator.index(), identifier)),
>    |                                       ^^^
> 
> error[E0308]: mismatched types
>   --> /home/.../.cargo/registry/src/github.com-1ecc6299db9ec823/timely-0.2.0/src/dataflow/channels/pact.rs:27:31
>    |
> 27 |          Box::new(Puller::new(puller, allocator.index(), identifier)))
>    |                               ^^^^^^ expected struct `std::boxed::Box`, found struct `timely_communication::allocator::thread::Puller`
>    |
>    = note: expected type `std::boxed::Box<timely_communication::Pull<dataflow::channels::message::Message<_, _>> + 'static>`
>               found type `timely_communication::allocator::thread::Puller<dataflow::channels::message::Message<T, D>>`
> 
> error: aborting due to 2 previous errors
> 
> error: Could not compile `timely`.
>

**Comment by frankmcsherry** [comment]
Hi! This is a breaking change that happened in Timely recently; let me track down which dependence is broken, and get back to you.

**Comment by frankmcsherry** [comment]
Should be fixed now, sorry. The problem was that timely 0.2.0 broke with an underlying change to the communication layer (and semver is hard / I am bad). Timely 0.3.0 should fix that, and I updated the requirements in `Cargo.toml` to require that version.

**Comment by de-code** [comment]
Thank you, that fixed it. You're super fast.
